# Stage 1: Build and train the model
FROM tensorflow/tensorflow:latest AS builder

# Set the working directory in the builder stage
WORKDIR /app

# Copy the Python script into the builder stage
COPY train_model.py /app/train_model.py

# Download the MNIST dataset
RUN python -c "from tensorflow.keras.datasets import mnist; mnist.load_data()"

# Run the script to train the model
RUN python train_model.py

# Stage 2: Final runtime stage
FROM tensorflow/tensorflow:latest

# Install Pillow
RUN pip install Pillow

# Set the working directory in the final stage
WORKDIR /app

COPY recognize_mnist.py /app/recognize_mnist.py

# Copy only the necessary files from the builder stage
COPY --from=builder /app/trained_model_*.h5 /app

# Specify the command to run the Python script
CMD ["python", "/app/recognize_mnist.py"]
